[target.xtensa-esp32s3-none-elf]
# Note: we typically flash via `make flash-monitor` (cargo-espflash).
# This runner is a convenient default for `cargo run`.
runner = "cargo espflash flash --monitor --chip esp32s3"

[env]
ESP_LOG="info"
# ESP32-S3R8 has embedded **octal** PSRAM. The esp-hal `psram` feature defaults to `quad`
# unless configured, which results in PSRAM auto-detect returning size 0 and early panics
# when we try to allocate the framebuffer.
ESP_HAL_CONFIG_PSRAM_MODE="octal"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
